// This file was automatically generated by [BuildCom](https://www.npmjs.com/package/buildcom)

import React from 'react'

%styleimport%
%typeString%

/* Render component */
export const %ComponentName%: React.FC = () => <div></div>

export default %ComponentName%
